name: Data Preprocessing Workflow

on:
  push:
    paths:
      - 'preprocessing/heart_disease_clean/**'

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn numpy

      - name: Run Preprocessing Script
        run: python preprocessing/automate_Nama-siswa.py

      - name: Commit and Push Clean Data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add preprocessing/namadataset_preprocessing/heart_disease_clean.csv
          git commit -m "Update preprocessed data" || echo "No changes to commit"
          git push